# AWS CREDENTIALS
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_DEFAULT_REGION = ""

# STMP SETTINGS
FROM_EMAIL = ""
TO_EMAIL = ""
SMTP_USERNAME = ""
SMTP_PASSWORD = ""
SMTP_HOST = ""
SMTP_PORT = 465

#CRON SETTINGS
CRON = "0 19 * * ? *"